# Generated by Django 4.1.5 on 2023-01-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpagedata',
            name='search_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
