# Generated by Django 4.1.5 on 2023-01-13 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_webpagedata_search_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='count_of_search',
            field=models.IntegerField(default=1, verbose_name='count of search'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='webpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='website.webpagedata'),
        ),
    ]
