# Generated by Django 4.1.5 on 2023-01-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_webpagedata_name_webpage_alter_webpagedata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_web',
            field=models.CharField(max_length=1255, primary_key=True, serialize=False),
        ),
    ]
